on:
  workflow_dispatch:
    inputs:
      V8_VERSION:
        description: 'V8_VERSION (leave blank for version as defined in V8/REV)'
        required: false
        type: string
        default: ''
      V8_BUILD_MODE:
        description: 'V8_BUILD_MODE'
        default: 'release-fuzz'
        required: true
        type: choice
        options:
        - release-fuzz
        - debug-no-fuzz
      V8_ASAN:
        description: 'V8_ASAN'
        type: boolean
        default: false
        required: false
      V8_TSAN:
        description: 'V8_TSAN'
        type: boolean
        default: false
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private target
        uses: actions/checkout@v3
        with:
         repository: ${{ secrets.CLONE_URL }}
         token: ${{ secrets.CLONE_URL_PAT }}
         persist-credentials: false
         path: target
      - name: "${{ inputs.V8_VERSION }} ${{ inputs.V8_BUILD_MODE }}"
        run: |
          echo $V8_VERSION
          echo $V8_BUILD_MODE
          echo $V8_ASAN
          echo $V8_TSAN          
          cd target/Cloud/Docker
          ./build.sh v8
        env:
          V8_VERSION: ${{ inputs.V8_VERSION }}
          V8_BUILD_MODE: ${{ inputs.V8_BUILD_MODE }}
          V8_ASAN: ${{ inputs.V8_ASAN || '' }}
          V8_TSAN: ${{ inputs.V8_TSAN || '' }}
      - name: Package
        run: |
          cd target/Cloud/Docker/V8Builder/out/
          # Will this expansion bite me? Probably.
          tar -czf $(echo *).tar.gz *
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz"
          artifactErrorsFailBuild: true
          # poor man's if-else, also see https://github.com/actions/runner/issues/409
          # $(condition && 'true case value/if branch value') || 'false case value/else branch value'
          tag: ${{ (inputs.V8_VERSION == '' && 'default-rev') || inputs.V8_VERSION }}
          token: ${{ secrets.RELEASE_PAT }}
          allowUpdates: true
